Repository bilby-dev/bilby, pull requests merged in 2024-11, with the labels that each got.

#842 ENH: implement time marginalization into multiband likelihood
  bilby/gw/likelihood/multiband.py
  test/gw/likelihood/marginalization_test.py
Labels: 10-100 lines, feature-request, likelihood

#828 BUG: make `get_cosmology` constistent with `set_cosmology`
  bilby/core/prior/base.py
  bilby/gw/cosmology.py
  test/core/prior/dict_test.py
  test/core/prior/prior_files/prior_with_cosmo_params.prior
Labels: bug, cosmology

#829 ENH: add Planck15_LAL cosmology
  bilby/gw/cosmology.py
  bilby/gw/prior.py
  test/gw/cosmology_test.py
Labels: enhancement

#855 TST: patch logger in tests
  test/gw/detector/psd_test.py
Labels: testing

#42 BUG: changed formatting for unused kwargs error message
  bilby/gw/source.py
  test/gw/source_test.py
Labels: bug, <10 lines

#48 [BUG] relative binning - correctly set last bin index
  bilby/gw/likelihood/relative.py
  test/gw/likelihood/relative_binning_test.py
Labels: bug, <10 lines

#850 Optimized rescale methods
  bilby/core/prior/dict.py
Labels: <10 lines, priors

#858 FEAT: Fix abs/rel path priority in result files.
  bilby/core/result.py
  test/core/result_test.py
Labels: bug

#859 CHANGELOG: update for v2.4.0
  CHANGELOG.md
Labels: release

#865 CI: specify `needs` for `pypi-publish`
  .github/workflows/publish.yml
Labels: ci
