Repository bilby-dev/bilby, pull requests merged in 2024-10, with the labels that each got.

#36 MAINT: migration updates
  .gitlab-ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.rst
  bilby/__init__.py
  bilby/core/sampler/dynesty.py
  docs/basics-of-parameter-estimation.txt
  docs/bilby-output.txt
  docs/compact-binary-coalescence-parameter-estimation.txt
  docs/conf.py
  docs/examples.txt
  docs/gw_prior.txt
  docs/installation.txt
  docs/likelihood.txt
  docs/plugins.txt
  docs/samplers.txt
  docs/writing-documentation.txt
  examples/README.rst
  setup.py
Labels: github migration

#824 DOC: update prior constraints docs
  docs/prior.txt
Labels: documentation, <10 lines, gitlab merge request

#822 MAINT: add sampler deprecation warning
  bilby/core/sampler/nessai.py
  bilby/core/sampler/polychord.py
  docs/plugins.txt
  docs/samplers.txt
Labels: sampling, gitlab merge request

#826 DOC: add invite link for slack
  README.rst
Labels: documentation

#28 [DEP][DOC]: 696 fix random seed documentation
  AUTHORS.md
  bilby/core/sampler/dynesty_utils.py
  examples/core_examples/alternative_samplers/linear_regression_bilby_mcmc.py
  examples/core_examples/alternative_samplers/linear_regression_pymc.py
  examples/core_examples/alternative_samplers/linear_regression_pymc_custom_likelihood.py
  examples/core_examples/gaussian_example.py
  examples/core_examples/gaussian_process_celerite_example.py
  examples/core_examples/gaussian_process_george_example.py
  examples/core_examples/grid_example.py
  examples/core_examples/hyper_parameter_example.py
  examples/core_examples/linear_regression.py
  examples/core_examples/linear_regression_grid.py
  examples/core_examples/linear_regression_unknown_noise.py
  examples/core_examples/linear_regression_with_Fisher.py
  examples/core_examples/occam_factor_example.py
  examples/core_examples/radioactive_decay.py
  examples/gw_examples/injection_examples/australian_detector.py
  examples/gw_examples/injection_examples/binary_neutron_star_example.py
  examples/gw_examples/injection_examples/bns_eos_example.py
  examples/gw_examples/injection_examples/bns_polytrope_eos_example.py
  examples/gw_examples/injection_examples/bns_spectral_pca_eos_example.py
  examples/gw_examples/injection_examples/calibration_example.py
  examples/gw_examples/injection_examples/calibration_marginalization_example.py
  examples/gw_examples/injection_examples/change_sampled_parameters.py
  examples/gw_examples/injection_examples/create_your_own_source_model.py
  examples/gw_examples/injection_examples/create_your_own_time_domain_source_model.py
  examples/gw_examples/injection_examples/custom_proposal_example.py
  examples/gw_examples/injection_examples/eccentric_inspiral.py
  examples/gw_examples/injection_examples/fake_sampler_example.py
  examples/gw_examples/injection_examples/how_to_specify_the_prior.py
  examples/gw_examples/injection_examples/marginalized_likelihood.py
  examples/gw_examples/injection_examples/multiband_example.py
  examples/gw_examples/injection_examples/non_tensor.py
  examples/gw_examples/injection_examples/plot_skymap.py
  examples/gw_examples/injection_examples/plot_time_domain_data.py
  examples/gw_examples/injection_examples/relative_binning.py
  examples/gw_examples/injection_examples/roq_example.py
  examples/gw_examples/injection_examples/sine_gaussian_example.py
  examples/gw_examples/injection_examples/standard_15d_cbc_tutorial.py
  examples/gw_examples/supernova_example/supernova_example.py
  examples/tutorials/compare_samplers.ipynb
  examples/tutorials/fitting_with_x_and_y_errors.ipynb
Labels: documentation

#823 BUG: Fix arviz bug import bug
  bilby/core/result.py
  test/core/result_test.py
Labels: bug, <10 lines, gitlab merge request

#838 DOC: fix misleading documentation for `set_strain_data_from_zero_noise`
  bilby/gw/detector/networks.py
  bilby/gw/detector/strain_data.py
Labels: documentation, <10 lines

#837 Remove double-backslashes from latex labels passed to matplotlib.
  bilby/core/result.py
Labels: <10 lines, plotting/visualisation, result/output
