Repository bilby-dev/bilby, pull requests merged in 2025-04, with the labels that each got.

#923 BUG: ensure directory exists when reweighting
  bilby/core/result.py
Labels: bug

#936 ENH: Dynesty: Allow printing dlogz below 1e-3
  bilby/core/sampler/dynesty.py
Labels: <10 lines

#930 BUG: Use "geocent" not "geocenter" where appropriate
  bilby/gw/conversion.py
Labels: bug, high priority
