Repository bilby-dev/bilby, pull requests merged in 2025-08, with the labels that each got.

#932 MAINT: define Planck15-LAL cosmology using LAL constants
  bilby/gw/cosmology.py
Labels: cosmology

#983 CI: add merge_group to enable merge queue
  .github/workflows/basic-install.yml
  .github/workflows/pages.yml
  .github/workflows/pre-commit.yml
  .github/workflows/unit-tests.yml
Labels: maintenance

#948 Allow search engine indexing of the documentation
  .github/workflows/pages.yml
  docs/conf.py
  docs/google063678b5c432c237.html
  docs/robots.txt
Labels: documentation
