Repository bilby-dev/bilby, pull requests merged in 2025-02, with the labels that each got.

#896 CI: remove constraint on matplotlib version
  .github/workflows/unit-tests.yml
Labels: <10 lines, ci

#873 ENH: add global meta data
  bilby/core/sampler/__init__.py
  bilby/core/utils/__init__.py
  bilby/core/utils/io.py
  bilby/core/utils/meta_data.py
  bilby/core/utils/random.py
  bilby/gw/cosmology.py
  bilby/gw/result.py
  test/core/utils_test.py
Labels: enhancement, >100 lines

#909 Restore numerical_relativity_file kwarg
  bilby/gw/source.py
Labels: bug

#911 BUG: fix incorrectly formatted raise statement
  bilby/core/result.py
  test/core/result_test.py
Labels: bug

#918 BUG: Allow posterior files with inconsistent priors to be merged.
  cli_bilby/bilby_result.py
Labels: bug

#899 ENH: Added the CBCResult class to all gw examples
  examples/gw_examples/data_examples/GW150914.py
  examples/gw_examples/data_examples/GW190425.py
  examples/gw_examples/injection_examples/australian_detector.py
  examples/gw_examples/injection_examples/binary_neutron_star_example.py
  examples/gw_examples/injection_examples/bns_eos_example.py
  examples/gw_examples/injection_examples/bns_polytrope_eos_example.py
  examples/gw_examples/injection_examples/bns_spectral_pca_eos_example.py
  examples/gw_examples/injection_examples/calibration_example.py
  examples/gw_examples/injection_examples/calibration_marginalization_example.py
  examples/gw_examples/injection_examples/change_sampled_parameters.py
  examples/gw_examples/injection_examples/create_your_own_source_model.py
  examples/gw_examples/injection_examples/create_your_own_time_domain_source_model.py
  examples/gw_examples/injection_examples/custom_proposal_example.py
  examples/gw_examples/injection_examples/eccentric_inspiral.py
  examples/gw_examples/injection_examples/fake_sampler_example.py
  examples/gw_examples/injection_examples/fast_tutorial.py
  examples/gw_examples/injection_examples/how_to_specify_the_prior.py
  examples/gw_examples/injection_examples/marginalized_likelihood.py
  examples/gw_examples/injection_examples/multiband_example.py
  examples/gw_examples/injection_examples/non_tensor.py
  examples/gw_examples/injection_examples/relative_binning.py
  examples/gw_examples/injection_examples/roq_example.py
  examples/gw_examples/injection_examples/sine_gaussian_example.py
Labels: example/tutorial

#920 ENH: Add InterferometerList time domain plotting
  bilby/gw/detector/networks.py
  test/gw/detector/networks_test.py
Labels: enhancement, plotting/visualisation

#915 MAINT: rework `GlobalMetaData` to inherit from `dict`
  bilby/core/result.py
  bilby/core/utils/__init__.py
  bilby/core/utils/env.py
  bilby/core/utils/meta_data.py
  bilby/gw/result.py
  docs/faq.txt
  examples/gw_examples/injection_examples/fast_tutorial.py
  test/core/utils_test.py
  test/gw/result_test.py
Labels: maintenance
