Repository bilby-dev/bilby, pull requests merged in 2025-01, with the labels that each got.

#885 CI: temporarily require matplotlib <3.10
  .github/workflows/unit-tests.yml
Labels: ci

#888 CI: specify python version and activate env
  .github/workflows/unit-tests.yml
Labels: ci

#891 TST: relax tolerance for prior test with cosmo parameters
  test/core/prior/dict_test.py
Labels: testing

#884 MAINT: avoid call to deprecated `scipy.special.btdtr` and `scipy.special.btdtri` functions
  bilby/core/prior/analytical.py
Labels: high priority

#887 TST: remove calls to deprecated `numpy.alltrue` function
  test/gw/detector/calibration_test.py
Labels: testing

#890 BUG: Update the resume file check to see if the file is empty
  bilby/core/sampler/dynesty.py
Labels: bug

#867 ENH: add cosmology to CBC result
  bilby/core/utils/io.py
  bilby/gw/result.py
  test/core/result_test.py
  test/gw/result_test.py
Labels: high priority, result/output

#853 BUG: issue warning when prior sampling efficiency is below 1e-3.
  bilby/core/prior/dict.py
Labels: bug, priors

#870 [BUG]: fixing dtypes being changed in plot_interferometer_waveform_posterior
  AUTHORS.md
  bilby/gw/result.py
Labels: bug

#820 [BUG] Fix passing mode_array in injection-waveform-arguments
  AUTHORS.md
  bilby/gw/source.py
  bilby/gw/utils.py
  test/gw/utils_test.py
Labels: bug
