Repository bilby-dev/bilby, pull requests merged in 2025-05, with the labels that each got.

#951 CHANGELOG: update for v2.5.1
  CHANGELOG.md
Labels: release

#922 DOC:Fixed README link for opening bilby_pipe issues
  README.rst
Labels: documentation

#946 ENH: plot_multiple: Allow plotting onto user-defined figure
  bilby/core/result.py
Labels: <10 lines, plotting/visualisation

#953 BUG: Fix sampling efficiency warning
  bilby/core/prior/dict.py
  test/core/prior/dict_test.py
Labels: bug
